[toolchain]
package_manager = "pnpm"

[features]
resolution = false
skip-lint = false

[programs.devnet]
pulso_anchor = "PuLsRBUdu4JxfP9tPU4WyNvWx7Vu2dS7NfCipm8YBmh"

[programs.localnet]
pulso_anchor = "PuLsRBUdu4JxfP9tPU4WyNvWx7Vu2dS7NfCipm8YBmh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
